---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metallb-system

resources:
  - namespace.yml
  - operatorgroup.yml
  - https://operatorhub.io/install/metallb-operator.yaml