---
- name: Update base system
  when: update_system
  ansible.builtin.dnf:
    name: '*'
    state: latest
    update_cache: true

- name: Set /etc/hosts file
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
