---
- name: Install the Kubernetes packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
    disable_excludes: kubernetes
  loop:
    - iproute-tc
    - nano
    - helm
    - git
    - ipvsadm
    - NetworkManager-tui
    - bash-completion
    - kubernetes-master
    - kubernetes-kubeadm
    - kubernetes-client
    - kubernetes-node

- name: Start and enable the kubelet service
  ansible.builtin.service:
    name: kubelet
    state: started
    enabled: true
