---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dns-pihole-2
  labels:
    app: dns-pihole-2
    service: dns-pihole
spec:
  selector:
    matchLabels:
      app: dns-pihole-2
      service: dns-pihole
  replicas: 1
  template:
    metadata:
      labels:
        app: dns-pihole-2
        service: dns-pihole
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "service"
                    operator: In
                    values:
                      - dns-pihole
              topologyKey: "kubernetes.io/hostname"
              namespaceSelector: {}
      containers:
        - name: dns-pihole-2
          securityContext:
            capabilities:
              add:
                - CHOWN
                - NET_BIND_SERVICE
                - NET_ADMIN
                - SETFCAP
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 512Mi
          image: docker.io/pihole/pihole:latest
          ports:
            - containerPort: 53
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: pihole-config
            - secretRef:
                name: pihole-secrets
          env:
            - name: ServerIP
              value: 192.168.42.12
            - name: FTLCONF_LOCAL_IPV4
              value: 192.168.42.12
            - name: VIRTUAL_HOST
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
