---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-vault-ui
  namespace: vault
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - vault-ui.apps.k8s.kemo.labs
  rules:
    - host: vault-ui.apps.k8s.kemo.labs
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: vault-ui
                port:
                  number: 8200