---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-vault-ui
  namespace: vault
  annotations:
    cert-manager.io/cluster-issuer: internal-step-ca-acme
    acme.cert-manager.io/http01-ingress-class: nginx
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - vault.apps.k8s.kemo.labs
      secretName: vault-ingress-cert
  rules:
    - host: vault-ui.apps.k8s.kemo.labs
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: vault-ui
                port:
                  number: 8200