---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: bulk-ssd
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "600"
  fsType: "ext4"
  diskSelector: "ssd,bulk"