---
apiVersion: v1
kind: Service
metadata:
  name: dns-core-1-tcp
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.42.9
    metallb.universe.tf/address-pool: lab-pool
    metallb.universe.tf/allow-shared-ip: "key-to-share-192.168.42.9"
spec:
  ports:
    - port: 53
      protocol: TCP
      targetPort: 53
      name: dns-tcp
    - port: 5353
      protocol: TCP
      targetPort: 5353
      name: dns-tcp-alt
  selector:
    app: dns-core-1
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: dns-core-1-udp
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.42.9
    metallb.universe.tf/address-pool: lab-pool
    metallb.universe.tf/allow-shared-ip: "key-to-share-192.168.42.9"
spec:
  ports:
    - port: 53
      protocol: UDP
      targetPort: 53
      name: dns-udp
    - port: 5353
      protocol: UDP
      targetPort: 5353
      name: dns-udp-alt
  selector:
    app: dns-core-1
  type: LoadBalancer