apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - ../../base

components:
  - ../../components/annotation-resource-tracking
  - ../../components/enable-plugins
  - ../../components/health-check-argocd
  - ../../components/health-check-olm
