apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: squid-cache
  labels:
    app: squid-proxy
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: bulk-ssd