---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: squid-certs
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app: squid-proxy
spec:
  data:
    - secretKey: squid-ca.pem # the key to be made in this k8s Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kemo-labs/credentials/certauth/squid-proxy # name of the secret under the target Vault path
        property: squid_ca_pem # # name of the key in that named Vault secret
  refreshInterval: 100s
  secretStoreRef:
    kind: ClusterSecretStore # SecretStore or ClusterSecretStore
    name: vault # name of the previousl created SecretStore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: squid-certs # name of the k8s Secret to make in this namespace
    template:
      engineVersion: v2
      type: Opaque # type of k8s Secret to make