---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: squid-log-rotate
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: squid-log-rotate
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - exec
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: squid-log-rotate
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: squid-log-rotate
subjects:
  - kind: ServiceAccount
    name: squid-log-rotate
