---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: squid-log-rotate
spec:
  schedule: "0 0 * * *" # Run every day at midnight
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: squid-log-rotate
            #image: registry.redhat.io/openshift4/ose-cli:latest
            image: quay.io/kenmoini/k8s-helper:latest
            imagePullPolicy: IfNotPresent
            command:
              - /bin/bash
              - -c
              - |
                #!/usr/bin/env bash

                kubectl get pods -l app=squid-proxy -n squid-proxy --no-headers -o custom-columns=":metadata.name" | while read -r pod ; do
                    kubectl exec -n squid-proxy $pod -- sh -c "squid -k rotate"
                done
          serviceAccountName: squid-log-rotate
          restartPolicy: OnFailure
