apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: squid-proxy

resources:
  - 00-namespace.yml
  - 01-cache-pvc.yml
  - 02-configmap.yml
  - 03-external-secrets.yml
  - 04-deployment.yml
  #- 05-logrotate-rbac.yml
  #- 06-logrotate-cronjob.yml
  - 07-service.yml