---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: step-ca-step-certificates-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  data:
    - secretKey: root_ca_key # the key to be made in this k8s Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kemo-labs/credentials/certauth/stepca # name of the secret under the target Vault path
        property: root_ca_key # # name of the key in that named Vault secret

    - secretKey: intermediate_ca_key # the key to be made in this k8s Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kemo-labs/credentials/certauth/stepca # name of the secret under the target Vault path
        property: intermediate_ca_key # # name of the key in that named Vault secret

    - secretKey: ssh_host_ca_key # the key to be made in this k8s Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kemo-labs/credentials/certauth/stepca # name of the secret under the target Vault path
        property: ssh_host_ca_key # # name of the key in that named Vault secret

    - secretKey: ssh_user_ca_key # the key to be made in this k8s Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kemo-labs/credentials/certauth/stepca # name of the secret under the target Vault path
        property: ssh_user_ca_key # # name of the key in that named Vault secret
  refreshInterval: 100s
  secretStoreRef:
    kind: ClusterSecretStore # SecretStore or ClusterSecretStore
    name: vault # name of the previousl created SecretStore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: step-ca-step-certificates-secrets # name of the k8s Secret to make in this namespace
    template:
      engineVersion: v2
      type: Opaque # type of k8s Secret to make

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: step-ca-step-certificates-certs
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  data:
    - secretKey: root_ca.crt # the key to be made in this k8s Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kemo-labs/credentials/certauth/stepca # name of the secret under the target Vault path
        property: root_ca_crt # # name of the key in that named Vault secret

    - secretKey: intermediate_ca.crt # the key to be made in this k8s Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kemo-labs/credentials/certauth/stepca # name of the secret under the target Vault path
        property: intermediate_ca_crt # # name of the key in that named Vault secret

    - secretKey: ssh_host_ca_key.pub # the key to be made in this k8s Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kemo-labs/credentials/certauth/stepca # name of the secret under the target Vault path
        property: ssh_host_ca_key_pub # # name of the key in that named Vault secret

    - secretKey: ssh_user_ca_key.pub # the key to be made in this k8s Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kemo-labs/credentials/certauth/stepca # name of the secret under the target Vault path
        property: ssh_user_ca_key_pub # # name of the key in that named Vault secret
  refreshInterval: 100s
  secretStoreRef:
    kind: ClusterSecretStore # SecretStore or ClusterSecretStore
    name: vault # name of the previousl created SecretStore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: step-ca-step-certificates-certs # name of the k8s Secret to make in this namespace
    template:
      engineVersion: v2
      type: Opaque # type of k8s Secret to make

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: step-ca-step-certificates-config
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  data:
    - secretKey: ca.json # the key to be made in this k8s Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kemo-labs/credentials/certauth/stepca # name of the secret under the target Vault path
        property: ca_json # # name of the key in that named Vault secret

    - secretKey: default.json # the key to be made in this k8s Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kemo-labs/credentials/certauth/stepca # name of the secret under the target Vault path
        property: default_json # # name of the key in that named Vault secret
  refreshInterval: 100s
  secretStoreRef:
    kind: ClusterSecretStore # SecretStore or ClusterSecretStore
    name: vault # name of the previousl created SecretStore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: step-ca-step-certificates-config # name of the k8s Secret to make in this namespace
    template:
      engineVersion: v2
      type: Opaque # type of k8s Secret to make

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: step-ca-step-certificates-ca-password
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  data:
    - secretKey: password # the key to be made in this k8s Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kemo-labs/credentials/certauth/stepca # name of the secret under the target Vault path
        property: ca_password # # name of the key in that named Vault secret
  refreshInterval: 100s
  secretStoreRef:
    kind: ClusterSecretStore # SecretStore or ClusterSecretStore
    name: vault # name of the previousl created SecretStore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: step-ca-step-certificates-ca-password # name of the k8s Secret to make in this namespace
    template:
      engineVersion: v2
      type: Opaque # type of k8s Secret to make

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: step-ca-step-certificates-ssh-host-ca-password
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  data:
    - secretKey: password # the key to be made in this k8s Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kemo-labs/credentials/certauth/stepca # name of the secret under the target Vault path
        property: ssh_host_ca_password # # name of the key in that named Vault secret
  refreshInterval: 100s
  secretStoreRef:
    kind: ClusterSecretStore # SecretStore or ClusterSecretStore
    name: vault # name of the previousl created SecretStore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: step-ca-step-certificates-ssh-host-ca-password # name of the k8s Secret to make in this namespace
    template:
      engineVersion: v2
      type: Opaque # type of k8s Secret to make

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: step-ca-step-certificates-ssh-user-ca-password
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  data:
    - secretKey: password # the key to be made in this k8s Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kemo-labs/credentials/certauth/stepca # name of the secret under the target Vault path
        property: ssh_user_ca_password # # name of the key in that named Vault secret
  refreshInterval: 100s
  secretStoreRef:
    kind: ClusterSecretStore # SecretStore or ClusterSecretStore
    name: vault # name of the previousl created SecretStore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: step-ca-step-certificates-ssh-user-ca-password # name of the k8s Secret to make in this namespace
    template:
      engineVersion: v2
      type: Opaque # type of k8s Secret to make

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: step-ca-step-certificates-certificate-issuer-password
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  data:
    - secretKey: password # the key to be made in this k8s Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kemo-labs/credentials/certauth/stepca # name of the secret under the target Vault path
        property: certificate_issuer_password # # name of the key in that named Vault secret
  refreshInterval: 100s
  secretStoreRef:
    kind: ClusterSecretStore # SecretStore or ClusterSecretStore
    name: vault # name of the previousl created SecretStore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: step-ca-step-certificates-certificate-issuer-password # name of the k8s Secret to make in this namespace
    template:
      engineVersion: v2
      type: Opaque # type of k8s Secret to make

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: step-ca-step-certificates-provisioner-password
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  data:
    - secretKey: password # the key to be made in this k8s Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kemo-labs/credentials/certauth/stepca # name of the secret under the target Vault path
        property: provisioner_password # # name of the key in that named Vault secret
  refreshInterval: 100s
  secretStoreRef:
    kind: ClusterSecretStore # SecretStore or ClusterSecretStore
    name: vault # name of the previousl created SecretStore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: step-ca-step-certificates-provisioner-password # name of the k8s Secret to make in this namespace
    template:
      engineVersion: v2
      type: Opaque # type of k8s Secret to make

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: step-ca-step-certificates-templates
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  data:
    - secretKey: ca.tpl # the key to be made in this k8s Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kemo-labs/credentials/certauth/stepca # name of the secret under the target Vault path
        property: ca_tpl # # name of the key in that named Vault secret

    - secretKey: config.tpl # the key to be made in this k8s Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kemo-labs/credentials/certauth/stepca # name of the secret under the target Vault path
        property: config_tpl # # name of the key in that named Vault secret

    - secretKey: known_hosts.tpl # the key to be made in this k8s Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kemo-labs/credentials/certauth/stepca # name of the secret under the target Vault path
        property: known_hosts_tpl # # name of the key in that named Vault secret

    - secretKey: sshd_config.tpl # the key to be made in this k8s Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kemo-labs/credentials/certauth/stepca # name of the secret under the target Vault path
        property: sshd_config_tpl # # name of the key in that named Vault secret

    - secretKey: step_config.tpl # the key to be made in this k8s Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kemo-labs/credentials/certauth/stepca # name of the secret under the target Vault path
        property: step_config_tpl # # name of the key in that named Vault secret

    - secretKey: step_includes.tpl # the key to be made in this k8s Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: kemo-labs/credentials/certauth/stepca # name of the secret under the target Vault path
        property: step_includes_tpl # # name of the key in that named Vault secret
  refreshInterval: 100s
  secretStoreRef:
    kind: ClusterSecretStore # SecretStore or ClusterSecretStore
    name: vault # name of the previousl created SecretStore
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: step-ca-step-certificates-templates # name of the k8s Secret to make in this namespace
    template:
      engineVersion: v2
      type: Opaque # type of k8s Secret to make