
# stepca-secret.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: step-ca-secrets
  namespace: step
type: Opaque
stringData:
  root_ca_key: |

  intermediate_ca_key: |

  ssh_host_ca_key: |

  ssh_user_ca_key: |


# stepca-certs.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: step-ca-certs
  namespace: step
type: Opaque
stringData:
  root_ca.crt: |

  intermediate_ca.crt: |

  ssh_host_ca_key.pub: |
    
  ssh_user_ca_key.pub: |
    

# stepca-config.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: step-ca-config
  namespace: step
type: Opaque
stringData:
  ca.json: |

  default.json: |


# stepca-ca-password-secret.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: step-ca-ca-password
  namespace: step
type: Opaque
stringData:
  password: "P455"

# stepca-ssh-host-ca-password-secret.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: step-ca-ssh-host-ca-password
  namespace: step
type: Opaque
stringData:
  password: "P455"

# stepca-ssh-user-ca-password-secret.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: step-ca-ssh-user-ca-password
  namespace: step
type: Opaque
stringData:
  password: "P455"

# stepca-certificate-issuer-password-secret.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: step-ca-certificate-issuer-password
  namespace: step
type: Opaque
stringData:
  password: "P455"

# steca-provisioner-password-secret.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: step-ca-provisioner-password
  namespace: step
type: Opaque
stringData:
  password: "P455"

