controller:
  # affinity: {}
  logLevel: 1
  ingressClass:
    name: nginx
  includeYear: false
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  enableCertManager: false
  hostNetwork: false
  enableLatencyMetrics: false
  setAsDefaultIngress: true
  terminationGracePeriodSeconds: 30
  nginxStatus:
    allowCidrs: 0.0.0.0/0
    enable: true
    port: 8080
  nginxReloadTimeout: 60000
  healthStatus: false
  appprotect:
    enable: false
  minReadySeconds: 1
  disableIPV6: false
  enableCustomResources: true
  globalConfiguration:
    create: false
    spec: {}
  reportIngressStatus:
    annotations: {}
    enable: true
    enableLeaderElection: true
    ingressLink: ''
  #kind: deployment
  kind: daemonset
  replicaCount: 1
  image:
    pullPolicy: IfNotPresent
    repository: nginx/nginx-ingress
    tag: 3.2.0-ubi
  enablePreviewPolicies: false
  service:
    externalIPs: []
    customPorts: []
    loadBalancerIP: ''
    annotations:
      metallb.universe.tf/address-pool: lab-pool
      metallb.universe.tf/loadBalancerIPs: 192.168.42.68
    externalTrafficPolicy: Local
    httpPort:
      enable: true
      port: 80
      targetPort: 80
    httpsPort:
      enable: true
      port: 443
      targetPort: 443
    loadBalancerSourceRanges: []
    extraLabels: {}
    type: LoadBalancer
    create: true
  readyStatus:
    enable: true
    initialDelaySeconds: 0
    port: 8081
  autoscaling:
    enabled: false
    #annotations: {}
    #maxReplicas: 3
    #minReplicas: 1
    #targetCPUUtilizationPercentage: 50
    #targetMemoryUtilizationPercentage: 50
  enableSnippets: false
  nginxDebug: false
  appprotectdos:
    enable: false
    #debug: false
    #maxDaemons: 0
    #maxWorkers: 0
    #memory: 0
  dnsPolicy: ClusterFirst
  enableExternalDNS: false
  enableTLSPassthrough: false
  enableOIDC: false
  healthStatusURI: /nginx-health
  #volumeMounts:
  #- name: trusted-ca
  #  mountPath: /etc/pki/tls/certs/cert-manager-tls-ca-bundle.crt
  #  subPath: ca-bundle.crt
  #volumes:
  #- name: trusted-ca
  #  configMap:
  #    name: trusted-ca
  #    defaultMode: 420
prometheus:
  create: true
  port: 9113
  scheme: http
rbac:
  create: true
readOnlyRootFilesystem: false

revisionHistoryLimit: 3

defaultBackend:
  ##
  enabled: true
  name: defaultbackend
  image:
    registry: quay.io
    image: kenmoini/ingress-custom-error-pages
    ## for backwards compatibility consider setting the full image url via the repository value below
    ## use *either* current default registry/image or repository format or installing chart by providing the values.yaml will fail
    ## repository:
    tag: "latest"
    pullPolicy: IfNotPresent
    runAsNonRoot: true
    # nobody user -> uid 65534
    runAsUser: 65534
    allowPrivilegeEscalation: false
    seccompProfile:
      type: RuntimeDefault
    readOnlyRootFilesystem: true