---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-config
data:
  TZ: America/New_York
  ADMIN_EMAIL: ken@kenmoini.com
  TEMPERATUREUNIT: f
  PIHOLE_DNS_: 208.67.220.220;208.67.222.222
  DNSMASQ_USER: root
  DNSMASQ_LISTENING: all
  PIHOLE_UID: "999"
  LANG: en_US.UTF-8
  LANGUAGE: en_US.UTF-8
  LC_CTYPE: "en_US.UTF-8"
  LC_NUMERIC: "en_US.UTF-8"
  LC_TIME: "en_US.UTF-8"
  LC_COLLATE: "en_US.UTF-8"
  LC_MONETARY: "en_US.UTF-8"
  LC_MESSAGES: "en_US.UTF-8"
  LC_PAPER: "en_US.UTF-8"
  LC_NAME: "en_US.UTF-8"
  LC_ADDRESS: "en_US.UTF-8"
  LC_TELEPHONE: "en_US.UTF-8"
  LC_MEASUREMENT: "en_US.UTF-8"
  LC_IDENTIFICATION: "en_US.UTF-8"
  LC_ALL: en_US.UTF-8
