---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    namespace: 'longhorn-system'
    server: https://kubernetes.default.svc
  project: local-cluster
  sources:
    - chart: longhorn
      helm:
        valueFiles:
          - $values/cluster-config/helm-values/longhorn.yml
      repoURL: 'https://charts.longhorn.io'
      targetRevision: 1.5.3
    - ref: values
      repoURL: 'https://github.com/kenmoini/ansible-fedora-k8s'
      targetRevision: main
    - repoURL: 'https://github.com/kenmoini/ansible-fedora-k8s'
      targetRevision: main
      path: lab-applications/system-glue/longhorn/
      #directory:
      #  recurse: true
      kustomize:
        version: v5.1.0
  syncPolicy:
    automated:
      allowEmpty: true
      # prune: false
    syncOptions:
      - CreateNamespace=true