---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: 'external-secrets'
    server: https://kubernetes.default.svc
  project: local-cluster
  sources:
    - chart: external-secrets
      helm:
        valueFiles:
          - $values/cluster-config/helm-values/external-secrets.yml
      repoURL: 'https://charts.external-secrets.io'
      targetRevision: 0.9.12
    - ref: values
      repoURL: 'https://github.com/kenmoini/ansible-fedora-k8s'
      targetRevision: main
    - repoURL: 'https://github.com/kenmoini/ansible-fedora-k8s'
      targetRevision: main
      path: lab-applications/external-secrets/
      kustomize:
        version: v5.1.0
  syncPolicy:
    automated:
      allowEmpty: true
      # prune: false
    syncOptions:
      - CreateNamespace=true