---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-pdns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  destination:
    namespace: 'step-ca'
    server: https://kubernetes.default.svc
  project: local-cluster
  sources:
    - chart: cert-manager-webhook-pdns
      helm:
        valueFiles:
          - $values/cluster-config/helm-values/cert-manager-pdns.yml
      repoURL: 'https://zachomedia.github.io/cert-manager-webhook-pdns'
      targetRevision: 2.5.0
    - ref: values
      repoURL: 'https://github.com/kenmoini/ansible-fedora-k8s'
      targetRevision: main
    - repoURL: 'https://github.com/kenmoini/ansible-fedora-k8s'
      targetRevision: main
      path: lab-applications/cert-manager-pdns/
      kustomize:
        version: v5.1.0
  syncPolicy:
    automated:
      allowEmpty: true
      # prune: false
    syncOptions:
      - CreateNamespace=true