---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - system-operators.yml
  - kubernetes-dashboard.yml
  - dns-core-2.yml
  #- metallb-operator.yml
  #- metallb-instance.yml
