---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - system-operators.yml
  - helm-nginx-ingress.yml
  - helm-longhorn.yml
  - kubernetes-dashboard.yml
  - lab-pdns-mysql.yml
  - dns-core-1.yml
  #- dns-core-2.yml
  - lab-ns-2.yml
  - dns-pihole-1.yml
  - dns-pihole-2.yml
  - system-glue.yml
  #- metallb-operator.yml
  #- metallb-instance.yml
