---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - system-operators.yml
  - 00-helm-longhorn.yml
  - 00-helm-nginx-ingress.yml
  - 01-system-glue.yml
  - 02-helm-vault.yml
  - 03-helm-external-secrets.yml
  - 04-helm-step-ca.yml
  - 05-lab-pdns-mysql.yml
  - 05-helm-cert-manager-pdns.yml
  - 06-dns-pihole-1.yml
  - 06-dns-pihole-2.yml
  - 10-lab-ns-1.yml
  - 10-lab-ns-2.yml
  - 20-lego-bridge.yml
  - 99-kubernetes-dashboard.yml
  - 99-site-kemo-labs.yml
  #- dns-core-1.yml
  #- dns-core-2.yml
  #- metallb-operator.yml
  #- metallb-instance.yml
