---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-pdns-mysql
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  sources:
    - repoURL: 'https://github.com/kenmoini/lab-powerdns'
      targetRevision: main
      path: deployment/pdns-mysql/
      #directory:
      #  recurse: true
      kustomize:
        version: v5.1.0
  project: local-cluster
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
    automated:
      #prune: true
      allowEmpty: true
      selfHeal: true # overrides changes made on the cluster that drift from git state
